language: go

dist: focal
sudo: required

go: "1.16.13"

jobs:
  include:
    - arch: amd64
    - arch: arm64-graviton2
      virt: vm
      group: edge
    - arch: amd64
      name: "amd64-race"
      if: type != pull_request
      env:
        - RACE=1
        - BASE_IMAGE=quay.io/cilium/cilium-runtime:ccd8a5a6b7d5d44a4153e32cdafdd83684f87379@sha256:747cec1d065ceff8a4267556a012d5792c3ec44b4baf4031e95e23ae6299d462
        - LOCKDEBUG=1
    - arch: arm64-graviton2
      name: "arm64-graviton2-race"
      if: type != pull_request
      env:
        - RACE=1
        - BASE_IMAGE=quay.io/cilium/cilium-runtime:ccd8a5a6b7d5d44a4153e32cdafdd83684f87379@sha256:747cec1d065ceff8a4267556a012d5792c3ec44b4baf4031e95e23ae6299d462
        - LOCKDEBUG=1
      virt: vm
      group: edge

if: branch = master OR type = pull_request

addons:
  apt:
    packages:
      - kernel-package
      - gnupg
      - libelf-dev
      - libncurses5

before_install: ./.travis/prepare.sh

before_script:
  - export PATH=/usr/local/clang/bin:$PATH

script: ./.travis/build.sh

notifications:
  email: false
